config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [ :index, :show, :destroy ]
  resources :tvshows
  resources :users
  resources :auth
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/login", to: "auth#new", as: "login"
  # Getting the Login Form

  post "/auth", to: "auth#create"
  # Getting the information from the user (via the form)

  delete "/auth", to: "auth#destroy"
  # Loggin Out
  
  post 'favorites/:id', to: "favorites#create"

  root 'auth#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tvshow

  validates :user_id, presence: true
  validates :tvshow_id, presence: true
  validates :user_id, uniqueness: { 
    scope: :tvshow_id, 
    message: "You can't favorite the same thing, twice!!" 
  }
  
  def self.this_tvshow
    @this_tvshow = Tvshow.find(params[:id])
  end 

end

app/models/tvshow.rb
require 'net/http'
require 'open-uri'
require 'json'


class Tvshow < ApplicationRecord
    has_many :favorites
    has_many :users, through: :favorites

    def self.get_popular_shows(page_number)
        url = "https://api.themoviedb.org/3/tv/popular?api_key=#{ENV['TMDB_API_KEY']}&page=#{page_number}"
        uri = URI.parse(url)
        response = Net::HTTP.get_response(uri)
        JSON.parse(response.body)
    end

    def find_favorite(user)
       user.favorites.find_by(tvshow_id: self.id)
    end

    

    # def self.search(search)
    #     if search
    #         tvshow = Tvshow.find_by(name: search)
    #         if tvshow 
    #             self.where(tvshow_id: tvshow)
    #         else
    #             Tvshow.all
    #         end
    #     else 
    #         Tvshow.all
    #     end 
    # end 
    
    # page1 = Tvshow.get_popular_shows(1)
    # page1["results"].count => 20

    # page1["results"][0]
    # page1["results"][0]["original_name"] => "See No Evil: The Moors Murders"
    # page1["results"][0]["name"] => "See No Evil: The Moors Murders" NAME
    # page1["results"][0]["genre_ids"] => [18]                        GENRE
    # page1["results"][0]["popularity"] => 500.623                    POPULARITY
    # page1["results"][0]["origin_country"] => ["GB"]
    # page1["results"][0]["vote_count"] => 8
    # page1["results"][0]["first_air_date"] => "2006-05-14"           FIRST AIR DATE
    # page1["results"][0]["backdrop_path"] => "/7AKhSfJHnVi0zXQS4eJirHDs22p.jpg"     BACKDROP
    # page1["results"][0]["original_language"] => "en"
    # page1["results"][0]["id"] => 11634
    # page1["results"][0]["vote_average"] => 6.6
    # page1["results"][0]["overview"] =>"The dramatisation of one of the most notorious killing sprees in British history."  OVERVIEW
    # page1["results"][0]["poster_path"] =>"/b71BaRjp9TwxUZodLGgSRIlkfL8.jpg"  POSTER
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    has_many :favorites, dependent: :destroy
    has_many :tvshows, through: :favorites

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :setup_auth

  def setup_auth
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find(@user_id)
      
    end
  end

  def authorized
    #byebug
    unless @logged_in
      flash[:message] = "Nice try, you need to log in."
      return redirect_to login_path
    end
  end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    # byebug
    if @user && @user.authenticate(params[:password])
      flash[:message] = "Logging in #{@user.name}."
      session[:user_id] = @user.id 

      redirect_to @user   
    else
      flash[:message] = "Invalid Username or Password."
      redirect_to new_auth_path
    end
  end

  def destroy
    #byebug
    session[:user_id] = nil 
    redirect_to login_path
  end 
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :find_favorite, only: [:show, :destroy]

    def index
        # if params[:search_term]
        #     @favorites = Favorite.where(name: params[:search_term])
        # else
        #     @favorites = Favorite.all
        # end
        @favorites = Favorite.all
    end
    
    def show
        current_tvshow
    end

    def new
        @favorite = Favorite.new
        current_tvshow
        current_user
    end

    def create
        #byebug
        current_user
        @favorite = Favorite.create(user_id: @user.id, tvshow_id: params[:id])
        if @favorite.valid?
            redirect_to user_path @favorite.user
        else
            flash[:errors] = @favorite.errors.full_messages
            redirect_to tvshows_path
        end
    end

    def destroy
        @favorite.destroy
        redirect_to tvshows_path
    end

    private

    # def search_and_destroy_favorite

    # end 

    def find_favorite
        current_user
        @favorite = Favorite.find_by(user_id: @user.id)
    end

    def favorite_params
        #byebug
        params.require(:favorite).permit(:user_id, :tvshow_id)
    end

    def favorite_button
        current_user
        current_tvshow
        #byebug
    end 

    def current_user
        @user = User.find(session[:user_id])
    end 

    def current_tvshow
        #byebug
        #@tvshow = Tvshow.find(params[:id]
    end 

end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
    before_action :check_user, only: [:index, :show]
    

    def index
        @page = params[:page]
        if params[:search_term]
            #@tvshows = Tvshow.where(name: params[:search_term])
            search = params[:search_term].downcase
            @tvshows = Tvshow.all.select { |tvshow|
                tvshow.name.downcase.include?(search)
            }
        else
            @page = params[:page]
            if @page
                @max = @page.to_i * 21
                @min = @max - 21
                @tvshows = Tvshow.where("id >= #{@min} and id <= #{@max}")
            else
                @tvshows = Tvshow.where("id <= 21")
            end
        end
    end

    def show
        find_tvshow
    end

    private

    def find_tvshow
        @tvshow = Tvshow.find(params[:id])
    end

    # def current_user
    #     @user = User.find(session[:user_id])
    # end 
    
    def current_user
        # if !!session[:user_id]
            @user = User.find(session[:user_id])
        # end
    end 

    def check_user
        if !current_user
            redirect_to login_path
        else
            current_user
        end 
    end

    # def tvshow_params
    #     params.require(:tvshow).permit(
    #     :name, 
    #     :overview,  
    #     :original_name, 
    #     :popularity,  
    #     :first_air_date, 
    #     :backdrop_path, 
    #     :poster_path
    #     )
    # end 
    
    # name:, 
    # overview:,  
    # original_name:, 
    # popularity:,  
    # first_air_date:, 
    # backdrop_path:, 
    # poster_path:

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [ :show ]

  def index
    all_users
  end 

  def new
    @user = User.new
  end 

  def create

    @user = User.create(user_params)

    if @user.valid?
      redirect_to @user
    else
      redirect_to new_user_path
    end

  end 

  def show
    find_user
  end 
  
  def edit 
   find_user
  end 

  def update
    find_user
    #byebug
    @user = @user.update(user_params)

    redirect_to user_path
  end 

  def destroy
    find_user
    @user.destroy

    redirect_to users_path
  end 

  private

  def find_user
    @user = User.find(session[:user_id])
  end

  # def current_user
  #   @current_user = User.find(session[:user_id])
  # end

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end 

  def all_users
    @users = User.all 
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1> All the favorites </h1>



<ul>
    <% @favorites.each do |favorite| %>
    <li>
        <%= favorite.user.name %> - <%= favorite.tvshow.name %> <%= button_to "-", favorite, method: :delete %>
    </li>
    <% end %>
</ul>

app/views/favorites/new.html.erb
<h1> Add a movie to your favorites! </h1>

<% if flash[:error] %>
    <ul>
        <% flash[:errors].each do |error| %>
        <li>
        error
        </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @favorite do |f| %>
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    <%= f.label :tvshow_id %>
    <%= f.collection_select :tvshow_id, Tvshow.all, :id, :name %>
    <%= f.submit "Add to favorites (+)"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvYou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if session[:user_id] %>
    <nav>
      <div class="nav-group-1">
        <button class="btn"> <%= link_to 'Home', "/tvshows" %></button>
        <button class="btn"><%= link_to 'Profile', "/users/1" %></button>
      </div>
      <div class="nav-group-2">
        <button class="btn"><%= link_to 'Log out', "/auth", method: :delete %></button>
      </div>
    </nav>
  <% else %>
  <nav>
    <h1 class="nav-h1">TV-You</h1>
  </nav>
  <% end %>
  <div class="divider"></div>
    <%= yield %>
  </body>
</html>

app/views/tvshows/index.html.erb
<div class="tvshows-page">
  <div class="index-header">
    <h1>Look at all these TV Shows!</h1>
    <div class="index-search"
        <%= form_tag "/tvshows", method: :get do %>
        <%= text_field_tag :search_term %>
        <%= submit_tag "Search" %>
        <% end %>
    </div>
    <div class="btn-container ">
      <% if @page.to_i == 1 %>
      <button class="btn btn__pages">
        <%= link_to "Next ≫", "/tvshows?page=#{@page.to_i + 1}" %>
      </button>
      <% else %>
      <button class="btn btn__pages">
        <%= link_to "≪ Prev", "/tvshows?page=#{@page.to_i - 1}" %>
      </button>
      <button class="btn btn__pages">
        <%= link_to "Next ≫", "/tvshows?page=#{@page.to_i + 1}" %>
      </button>
      <% end %>
    </div>
  </div>
  <div class="tvshows_list">
    <% @tvshows.each do |tvshow| %>
    <div class="index-tvshow u-center-text u-margin-bottom-small">
      <a href="<%= tvshow_path(tvshow) %>">
        <img
          class="poster"
          src="https://image.tmdb.org/t/p/w500<%= tvshow.poster_path %>"
          alt="tvshow.name"
        />
        <h6 class="index-tvshow-name"><%= tvshow.name %></h6>
      </a>
      <!-- LINK -->

      <% if @user.tvshows.include?(tvshow) %>
      <button class="btn btn--red">
        <%= link_to 'Remove from Favorites!',
        favorite_path(tvshow.find_favorite(@user)), method: :delete %>
      </button>
      <% else %>
      <button class="btn btn--green">
        <%= link_to "Add to FAVORITES!!!", "/favorites/#{tvshow.id}", method:
        :post %>
      </button>
      <% end %>
      <!-- CONDITIONAL -->
    </div>
    <!-- index-tvshow -->

    <% end %>
    <!-- @tvshows.each -->
  </div>
  <!-- .tvshows_list -->
</div>
<!-- .tvshows-page -->

app/views/tvshows/show.html.erb
<div class="tvshow-container">
  <h1><%= @tvshow.name %></h1>

  <img
    class="show-backdrop"
    src="https://image.tmdb.org/t/p/w500<%= @tvshow.backdrop_path %>"
    alt="<%= @tvshow.name %> backdrop"
  />

  <p><%= @tvshow.overview %></p>

  <p>First Aired: <%= @tvshow.first_air_date %></p>
  <% if @tvshow.original_name != @tvshow.name %>
  <p>Original Name: <%= @tvshow.original_name %></p>
  <% end %> <% if @user.tvshows.include?(@tvshow) %> <%= button_to 'Remove from
  Favorites!', favorite_path(@tvshow.find_favorite(@user)), method: :delete %>
  <% else %> <%= button_to "Add to FAVORITES!!!", "/favorites/#{@tvshow.id}" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1> Edit User </h1> 

<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> 
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1> All Users ( FOR DEV USE ONLY!!!!) </h1>

<%= link_to "Create User", new_user_path %>

<% @users.each do |user| %>
  <p> <%= link_to user.name, user %> </p>
<% end %>

app/views/users/new.html.erb
<h1> User Registration </h1> 

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %> 
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<div class="user-container">
  <h1> <%= @user.name %> </h1>

  <% if @user.favorites %>
    <% @user.favorites.each do |favorite| %>
      <p> <%= link_to favorite.tvshow.name, favorite.tvshow %> </p>
    <% end %>
  <% end %> 

  <%= link_to "Edit User", edit_user_path(@user) %>
  <p> <%= button_to 'Delete this user', user_path(@user),
              data: {:confirm => 'Are you sure?'}, :method => :delete %>
  </p>
</div>